In [1]:
#https://www.tensorflow.org/guide/tensor
import tensorflow as tf

In [2]:
tf.__version__

'2.6.0'

In [3]:
#initialize two constants
x1=tf.constant([1,2,3,4])
x2=tf.constant([5,6,7,8])
#multiply
result = tf.multiply(x1,x2)
#print the result
print(result)

tf.Tensor([ 5 12 21 32], shape=(4,), dtype=int32)


In [5]:
x1=tf.constant([1,2,3,4])
x2=tf.constant([5,6,7,8])
#multiply
result = tf.multiply(x1,x2)

#print the result
print(result)


tf.Tensor([ 5 12 21 32], shape=(4,), dtype=int32)


In [4]:
hello = tf.constant('Hello, Tensorflow!')
tf.print(hello)

Hello, Tensorflow!


In [5]:
# This will be an int32 tensor by default; see "dtypes" below.
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [6]:
# Let's make this a float tensor.
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [7]:
# If you want to be specific, you can set the dtype (see below) at creation time
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


In [10]:
# There can be an arbitrary number of
# axes (sometimes called "dimensions")
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)
