In [2]:
import tensorflow as tf

In [3]:
mnist =tf.keras.datasets.mnist

In [4]:
(x_train,y_train),(x_test,y_test)=mnist.load_data()

NameError: name 'dtype' is not defined

In [4]:
x_train.shape

(60000, 28, 28)

In [5]:
x_test.shape

(10000, 28, 28)

In [6]:
model = tf.keras.models.Sequential(
[
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
]
)

In [7]:
predictions= model(x_train[:1]).numpy()
print(predictions)

[[   0.36709785   -9.772356    120.99731     -14.385626     60.316257
  -145.4656      170.72853     -11.201626     53.076027    197.72913   ]]


In [8]:
tf.nn.softmax(predictions).numpy()

array([[0.0000000e+00, 0.0000000e+00, 4.7401745e-34, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 1.8784106e-12, 0.0000000e+00,
        0.0000000e+00, 1.0000000e+00]], dtype=float32)

In [9]:
loss_fn=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
print(loss_fn)

In [10]:
loss_fn(y_train[:1],predictions).numpy()

343.19473

In [11]:
model.compile(optimizer='adam',loss=loss_fn,metrics=['accuracy'])

In [12]:
model.fit(x_train,y_train,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 8s 4ms/step - loss: 2.3804 - accuracy: 0.7761
Epoch 2/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.5640 - accuracy: 0.8524
Epoch 3/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.4694 - accuracy: 0.8772
Epoch 4/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.4123 - accuracy: 0.8937
Epoch 5/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.3924 - accuracy: 0.9010


In [13]:
model.evaluate(x_test,y_test,verbose=2)

313/313 - 1s - loss: 0.2871 - accuracy: 0.9310


[0.28714871406555176, 0.9309999942779541]

In [14]:
probablility_model=tf.keras.Sequential(
[
    model,
    tf.keras.layers.Softmax()
])

In [15]:
probablility_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0.00000000e+00, 1.83972795e-14, 2.22349448e-11, 1.39073535e-14,
        1.97210102e-16, 6.51395022e-32, 3.07530284e-34, 1.00000000e+00,
        1.57269628e-33, 9.09930903e-15],
       [8.07456010e-15, 8.95471253e-09, 1.00000000e+00, 1.76684191e-17,
        3.37687825e-33, 1.80928626e-25, 2.51854256e-13, 3.38479272e-13,
        1.79748706e-26, 0.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 5.18653740e-12, 1.98608059e-26,
        1.07127241e-16, 0.00000000e+00, 3.34270202e-15, 1.08446899e-12,
        2.39862344e-19, 2.00895317e-28],
       [9.99997735e-01, 2.02519598e-31, 2.38163511e-09, 1.63075334e-11,
        9.15066470e-23, 4.07907493e-11, 2.23691586e-06, 1.05606024e-09,
        1.14622548e-11, 1.09890872e-12],
       [8.81606965e-08, 2.77612120e-08, 5.50175086e-04, 7.03461681e-12,
        9.79317784e-01, 8.55825565e-05, 2.92845471e-06, 2.00374406e-02,
        4.03353306e-09, 5.98221095e-06]], dtype=float32)>